variables:

before_script:
  - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
  - docker login -u gavin.zhang -p $CI_JOB_TOKEN $CI_REGISTRY

stages:
  - build
  - deploy

stages:
  - build
  - deploy

build:
  stage: build
  script: 
    - ./build.sh
    - docker push registry.gitlab.com/gavin.zhang/eshop/catalog
    - docker push registry.gitlab.com/gavin.zhang/eshop/ordering
    - docker push registry.gitlab.com/gavin.zhang/eshop/web.bff.shopping
    - docker push registry.gitlab.com/gavin.zhang/eshop/basket
    - docker push registry.gitlab.com/gavin.zhang/eshop/webspa

deploy:
  stage: deploy
  script:
    - docker-compose -H ssh://ubuntu@13.236.121.99 -f docker-compose.yml pull
    - PIC_HOST=13.236.121.99 docker-compose -H ssh://ubuntu@13.236.121.99 -f docker-compose.yml up

