variables:
  AWS_HOST: "13.236.121.99"
  AWS_DOCKER: "ssh://ubuntu@$AWS_HOST"

before_script:
  - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
  - docker login -u gavin.zhang -p $MY_TOKEN $CI_REGISTRY

stages:
  - build
  - deploy

build:
  stage: build
  script: 
    - ./build.sh
    - docker push registry.gitlab.com/gavin.zhang/eshop/catalog
    - docker push registry.gitlab.com/gavin.zhang/eshop/ordering
    - docker push registry.gitlab.com/gavin.zhang/eshop/web.bff.shopping
    - docker push registry.gitlab.com/gavin.zhang/eshop/basket
    - docker push registry.gitlab.com/gavin.zhang/eshop/webspa

deploy:
  stage: deploy
  script:
    - docker-compose -H $AWS_DOCKER -f docker-compose.yml -f docker-compose.prod.yml pull
    - COMPOSE_HTTP_TIMEOUT=600 PIC_HOST=$AWS_HOST DB_HOST=$DB_HOST DB_USER=$DB_USER DB_PASSWORD=$DB_PASSWORD docker-compose -H $AWS_DOCKER -f docker-compose.yml -f docker-compose.prod.yml up -d

