before_script:
  - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
  - docker login -u gavin.zhang -p v8yY5nA73bCqdTrNFfAs $CI_REGISTRY

build:
  stage: build
  script: 
    - ./build.sh
    - docker push registry.gitlab.com/gavin.zhang/eshop/catalog
    - docker push registry.gitlab.com/gavin.zhang/eshop/ordering
    - docker push registry.gitlab.com/gavin.zhang/eshop/web.bff.shopping
    - docker push registry.gitlab.com/gavin.zhang/eshop/basket
    - docker push registry.gitlab.com/gavin.zhang/eshop/webspa


