version: '3.4'

services:
  catalog.api:
    image: ${DOCKER_REGISTRY}/catalog
    entrypoint: ["/wait-for-it.sh", "rabbitmq:15672", "--timeout=30", "--", "java", "-jar", "/app.jar"]

  basket.api:
    image: ${DOCKER_REGISTRY}/basket
    entrypoint: ["/wait-for-it.sh", "rabbitmq:15672", "--timeout=30", "--", "java", "-jar", "/app.jar"]

  ordering.api:
    image: ${DOCKER_REGISTRY}/ordering
    entrypoint: ["/wait-for-it.sh", "rabbitmq:15672", "--timeout=30", "--", "java", "-jar", "/app.jar"]

  api.gateway:
    image: ${DOCKER_REGISTRY}/web.bff.shopping
    depends_on:
      - catalog.api
      - basket.api
      - ordering.api

  web.spa:
    image: ${DOCKER_REGISTRY}/webspa
    depends_on:
      - api.gateway
