version: '3.4'

services:
  sql.data:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
#requered when access outside docker, i.e. from application not running by docker
    ports: ["5432:5432"]
    volumes:
      - ./data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  catalog.api:
    image: ${DOCKER_REGISTRY}/catalog
    build:
      context: ./services/catalog
    depends_on:
      - sql.data
      - rabbitmq
    environment:
      - DB_URL=jdbc:postgresql://sql.data:5432/postgres
      - RABBITMQ_HOST=rabbitmq
#access from browser so cannot use service name defined in compose file
      - PICTURE_SERVER_URL=http://${PIC_HOST:-localhost}:8080/pics
    ports:
      - "8080:8080"
    entrypoint: ["/wait-for-it.sh", "rabbitmq:15672", "--timeout=30", "--", "java", "-jar", "/app.jar"]

  basket.api:
    image: ${DOCKER_REGISTRY}/basket
    build:
      context: ./services/basket
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
    ports:
      - "8083:8080"
    entrypoint: ["/wait-for-it.sh", "rabbitmq:15672", "--timeout=30", "--", "java", "-jar", "/app.jar"]

  ordering.api:
    image: ${DOCKER_REGISTRY}/ordering
    build:
      context: ./services/ordering
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
    ports:
      - "8082:8080"
    entrypoint: ["/wait-for-it.sh", "rabbitmq:15672", "--timeout=30", "--", "java", "-jar", "/app.jar"]

  api.gateway:
    image: ${DOCKER_REGISTRY}/web.bff.shopping
    build:
      context: ./api.gateway/web.bff.shopping
    depends_on:
      - catalog.api
      - basket.api
      - ordering.api
    environment:
      - CATALOG_API_URL=http://catalog.api:8080
      - BASKET_API_URL=http://basket.api:8080
    ports:
      - "8081:8080"

  web.spa:
    image: ${DOCKER_REGISTRY}/webspa
    build:
      context: ./webSPA
    depends_on:
      - api.gateway
    environment:
      - API_GATEWAY=http://api.gateway:8080
    ports:
      - "8085:80"
