version: '3.4'

services:
  sql.data:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
#requered when access outside docker, i.e. from application not running by docker
    ports: ["5432:5432"]
    volumes:
      - ./data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  catalog.api:
    image: catalog
    environment: 
      - DB_URL=jdbc:postgresql://sql.data:5432/postgres
    ports: ["8080:8080"]
    depends_on:
      - sql.data
      - rabbitmq

  ordering.api:
    image: ordering
    depends_on:
      - rabbitmq

  api.gateway:
    image: web.bff.shopping
    environment:
      - CATALOG_API_URL=http://catalog.api:8080
    ports: ["8081:8080"]
    depends_on:
      - catalog.api

  web.spa:
    image: webspa
    environment:
      - API_GATEWAY=http://api.gateway:8080
    ports: ["8085:80"]
    depends_on:
      - api.gateway
