version: '3.4'

services:
  catalog.api:
    environment:
      - DB_URL=jdbc:postgresql://${DB_HOST}:5432/eshopdb
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - RABBITMQ_HOST=10.0.10.12
#access from browser so cannot use service name defined in compose file
      - PICTURE_SERVER_URL=http://${PIC_HOST:-localhost}:8080/pics
    ports:
      - "8080:8080"

  basket.api:
    environment:
      - RABBITMQ_HOST=10.0.10.12

  ordering.api:
    environment:
      - RABBITMQ_HOST=10.0.10.12
    ports:
      - "8082:8080"

  api.gateway:
    environment:
      - CATALOG_API_URL=http://catalog.api:8080
      - BASKET_API_URL=http://basket.api:8080
    ports:
      - "8081:8080"

  web.spa:
    environment:
      - API_GATEWAY=http://api.gateway:8080
    ports:
      - "8085:80"
