version: '3.4'

services:
  catalog.api:
    build:
      context: ./services/catalog
    image: ${DOCKER_REGISTRY}/catalog

  basket.api:
    build:
      context: ./services/basket
    image: ${DOCKER_REGISTRY}/basket

  ordering.api:
    build:
      context: ./services/ordering
    image: ${DOCKER_REGISTRY}/ordering

  api.gateway:
    build:
      context: ./api.gateway/web.bff.shopping
    image: ${DOCKER_REGISTRY}/web.bff.shopping
    depends_on:
      - catalog.api
      - basket.api
      - ordering.api

  web.spa:
    build:
      context: ./webSPA
    image: ${DOCKER_REGISTRY}/webspa
    depends_on:
      - api.gateway
